### ISSUE TITLE
Instagram feed

### ISSUE THREAD

**Issue by Alphenus** [fyysikkokilta/fktheme2019#2]
## Issue is about..
  - a Feature Request

Get an instagram feed to front-page

## TODO
- [x] Set up API tokens
- [x] Integrate API token to wordpress settings
- [x] Show images on front-page
- [x] Make it nice and linked

* Working code is already available at @Alphenus 's other repo (Chaperon website)
