### ISSUE TITLE
Calendar feed

### ISSUE THREAD

**Issue by Alphenus** [fyysikkokilta/fktheme2019#3]
## Issue is about..
a Feature Request

Get data from Guild's google calendar API and process it to show nicely on front-page

## TODO:

- [x] Get data form Google API
- [x] Cache data in WP
- [x] Fetch data to front
- [x] Set icons according to the event type
- [x] Show events in nice grid

## OPTIONAL

- [ ] Change calendars and icons in dashboard

**Comment by Alphenus** [comment]
Data fetching is now working, and data is cached in WP using WordPress transients.
Styling is still required.
